### ISSUE TITLE
Error: Unexpected "T" at position 0 in state START

### ISSUE THREAD

**Issue by doug-wade** [chrisdickinson/npm-get-dependents#4]
I'm trying to get the dependents for a package, and I can't seem to get it to work as anticipated. Here's my code snippet:

```
var getDependents = require("npm-get-dependents");

getDependents("bluebird", function (err, packages) {
  packages.forEach(console.log); // each package is a string.
});
```

I'm getting the error

```
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected "T" at position 0 in state START
    at Parser.proto.charError (/home/doug/workspace/npm-get-top-dependents-client/node_modules/npm-get-dependents/node_modules/jsonparse/jsonparse.js:84:16)
    at Parser.proto.write (/home/doug/workspace/npm-get-top-dependents-client/node_modules/npm-get-dependents/node_modules/jsonparse/jsonparse.js:112:23)
    at Stream.<anonymous> (/home/doug/workspace/npm-get-top-dependents-client/node_modules/npm-get-dependents/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/home/doug/workspace/npm-get-top-dependents-client/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (node:internal/streams/readable:754:22)
    at IncomingMessage.emit (node:events:527:28)
    at IncomingMessage.Readable.read (node:internal/streams/readable:527:10)
    at flow (node:internal/streams/readable:1011:34)
    at resume_ (node:internal/streams/readable:992:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Stream instance at:
    at Stream.onerror (node:internal/streams/readable:773:14)
    at Stream.emit (node:events:527:28)
    at Parser.parser.onError (/home/doug/workspace/npm-get-top-dependents-client/node_modules/npm-get-dependents/node_modules/JSONStream/index.js:100:12)
    at Parser.proto.charError (/home/doug/workspace/npm-get-top-dependents-client/node_modules/npm-get-dependents/node_modules/jsonparse/jsonparse.js:84:8)
    at Parser.proto.write (/home/doug/workspace/npm-get-top-dependents-client/node_modules/npm-get-dependents/node_modules/jsonparse/jsonparse.js:112:23)
    [... lines matching original stack trace ...]
    at IncomingMessage.Readable.read (node:internal/streams/readable:527:10)
```

Have I done something wrong?

**Comment by aegilops** [comment]
No, you didn't do anything wrong.

I debugged this myself just now. If you change part of the code of the module to:

```javascript
      res.on('data', function (chunk) {
        console.log(chunk.toString('utf8'));
      });
```

you can log out the response from the npm server. It reads:

```
The API was deprecated
```

That means this module (and others like it) are now defunct.

**Comment by doug-wade** [comment]
@aegilops Thanks for checking it out for me! Would you like a PR adding a disclaimer to the README?

**Comment by aegilops** [comment]
It's not my project - I just tried to use it - but that's a good idea
